language: scala
scala:
    - "2.10.4"

jdk:
    - oraclejdk7
    - openjdk7

script:
    - make test-travis

sudo: false

cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot/

branches:
    only:
        - master